import hashlib      # Used to calculate MD5 sum
import os
import time
import sys
import schedule
import smtplib
from email.message import EmailMessage

def CalculateCheckSum(FileName):
    fobj = open(FileName , "rb")

    # Called md5 algorithm to calculate check sum
    hobj = hashlib.md5()

    # Read the data from file only 1024 size
    Buffer = fobj.read(1024)

    while(len(Buffer) > 0):
        hobj.update(Buffer)     # Push the data to the md5 algorithm object(hobj)
        Buffer = fobj.read(1024)    # Read the next data form the file 1024 byte(standard number)

    fobj.close()

    # Calculate Check Sum
    return hobj.hexdigest()

def FindDuplicate(DirectoryName = "Marvellous"):
    Ret = False

    # checks directory exists or not
    Ret = os.path.exists(DirectoryName)
    if (Ret == False):
        print("There is no such directory")
        return
    
    # checks is it directory
    Ret = os.path.isdir(DirectoryName)
    if Ret == False : 
        print("It is not a directory")
        return
    
    Duplicate = {}

    for FolderName, SubFoldarName , FileName in os.walk(DirectoryName):
        for fname in FileName:
            fname = os.path.join(FolderName,fname)
            CheckSum = CalculateCheckSum(fname)         #Calculate check sum for every file

            #  Stores only unique data in the Duplicate(Dictionary)
            if CheckSum in Duplicate:
                Duplicate[CheckSum].append(fname)
            else:
                Duplicate[CheckSum] = [fname]
            
    return Duplicate


def DeleteDuplicate(s_email, a_password, r_email , Path = "Marvellous"):
    Border = "-" * 60
    timestamp = time.ctime()
    FileName = "DuplicateLog_%s.log" %(timestamp)
    FileName = FileName.replace(" ","_")
    FileName = FileName.replace(":","_")

    fobj = open(FileName,"w")
    fobj.write(Border + "\n")
    fobj.write("This is a log file created by duplicate file remover.\n")
    fobj.write("This log file contains the list of duplicate files deleted.\n")
    fobj.write(Border + "\n")

    start_time = time.time()

    MyDict = FindDuplicate(Path)

    Result = list(filter(lambda x : len(x) > 1, MyDict.values()))

    Count = 0
    Cnt = 0
    for value in Result:
        for subvalue in value:
            Count = Count + 1
            if(Count > 1):
                fobj.write(f"Deleted File : {subvalue}\n")
                os.remove(subvalue)
                Cnt = Cnt + 1
        Count = 0

    end_time = time.time()
    Total_time = end_time - start_time

    fobj.write(f"Total Deleted File : {Cnt}\n")
    fobj.write(Border + "\n")
    fobj.write(f"Total time taken by Application : {Total_time} sec\n")
    fobj.write(Border + "\n")
    fobj.close()

    SendLogMail(
        sender_email= s_email,
        app_password= a_password,
        receiver_email= r_email,
        log_file_path= FileName
    )


def SendLogMail(sender_email, app_password, receiver_email, log_file_path):
    try:
        msg = EmailMessage()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = "Duplicate File Remover - Log Report"

        msg.set_content(
            "Hello,\n\n"
            "Please find attached the log file generated by the automation script.\n\n"
            "Regards,\n"
            "Duplicate File Removal Automation Script"
        )

        # Attach Log file
        if os.path.exists(log_file_path):
            Lobj = open(log_file_path,"rb")
            file_data = Lobj.read()
            file_name = os.path.basename(log_file_path)

            msg.add_attachment(
                file_data,
                maintype = 'application',
                subtype = 'octet-stream',
                filename = file_name          
            )        
        
        else:
            print("Log file not found")
            return

        # SMTP Connection
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, app_password)
            server.send_message(msg)

        print("Log file email sent successfully.")

    except Exception as e:
        print("Error while sending mail:", e)


def main():
    Border = "-" * 60
    # Header
    print(Border)
    print("-------Welcome to Duplicate File Remover Application--------")
    print(Border)

    # Check number of arguments
    if(len(sys.argv) == 2):

        if (os.path.exists(sys.argv[1]) == True):

            sender_email = input("Enter sender email address: ")
            app_password = input("Enter app password: ")
            receiver_email = input("Enter receiver email address: ")

            SchTime = int(input("Enter the schedule time in minutes to run the application: "))
            schedule.every(SchTime).minutes.do(DeleteDuplicate, sender_email, app_password, receiver_email, sys.argv[1])
            print(f"Application scheduled to run every {SchTime} minutes.")
    
            # Start the scheduler
            print("Scheduler started. Press Ctrl + C to stop.")
            try:
                while True:
                    schedule.run_pending()
                    time.sleep(1)

            except KeyboardInterrupt:
                print("\nScheduler stopped by user.")
                sys.exit(0)

        # Help & Usage
        elif((sys.argv[1] == "--h") or (sys.argv[1] == "--H")):
            print("This application is used to remove duplicate files from- \nthe specified directory.")
            print("You need to provide one argument as a directory name.")
            
        elif((sys.argv[1] == "--u") or (sys.argv[1] == "--U")):
            print("Use the given script as ")
            print("Usage : ApplicationName.py DirectoryName")
            print("Argument1 : Directory Name")

        else:
            print("Use the give flags as : ")
            print("--u : Use to display the Usage")
            print("--h : Use to display the Help")
            
    else:
        print("Invalid number of command line arguments.") 
        print("Please specify the name of directory.")
        print("Use the give flags as : ")
        print("--u : Use to display the Usage")
        print("--h : Use to display the Help")


    # Footer
    print(Border)
    print("---Thank you for using Duplicate File Remover Application---")
    print(Border)


if __name__ == "__main__":
    main()